FROM python:3.12-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the image
ADD . /app

WORKDIR /app
RUN uv sync

ENV PATH="/app/.venv/bin:$PATH"

RUN useradd -m -u 8877 nonroot
RUN mkdir -p /app/overtourism/overtourism/database && chown -R 8877:8877 /app
USER 8877

EXPOSE 8001

# Run the model-computation FastAPI application by default.
ENTRYPOINT ["fastapi", "run", "--host", "0.0.0.0", "--port", "8001", "/app/overtourism/layer_3/api/main.py"]
