[project]
name = "overtourism"
version = "0.1.0"
description = "Trentino overtourism analysis and modeling"
requires-python = ">=3.12"
dependencies = [
    "civic-digital-twins==0.11.0",
    "digitalhub==0.15.11",
    "fastapi[standard]==0.141.1",
    "geojson==3.3.0",
    "geopandas==1.1.4",
    "matplotlib==3.11.2",
    "numpy==2.5.3",
    "orjson==3.12.0",
    "pandas==3.0.5",
    "plotly==7.1.0",
    "pyarrow==25.0.1",
    "scikit-learn==1.9.1",
    "scipy==1.18.1",
    "streamlit-option-menu==0.4.0",
    "streamlit==1.64.0",
    "sqlalchemy==2.0.54",
    "unidecode==1.4.0",
    "networkx==3.6.1",
    "contextily==1.7.1",
    "matplotlib-scalebar==0.9.0",
    "osmnx==2.1.1",
    "PyJWT[crypto]==2.14.0",
    "polars==1.44.2",
    "haversine==2.9.0",
    "tqdm==4.70.1",
    "seaborn==0.13.2",
    "gtfs_kit==13.0.1",
    "openpyxl==3.1.5",
    "psycopg[binary,pool]==3.3.5",
    "zstandard==0.25.0",
    "httpx2"
]
license = "Apache-2.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = ["black==26.5.1", "pytest==9.1.1", "pytest-cov==7.1.0"]
