# Settings of the data-preparation update pipeline.
# Edit this file as needed or use it as template for new updates

datasets:
  popolazione:
    enabled: true
    sources:
      - file: popolazione_2026_ISPAT.csv
        reader: csv
        adapter: popolazione_ispat_1jan
        adapter_kwargs: {year: 2025}        # uses column "Popolazione residente al 1.1.2025"

  strutture:
    enabled: true
    sources:
      - file: numero_strutture_ISPAT_2025.xlsx
        reader: excel
        reader_kwargs: {header: [0, 1]}
        adapter: strutture_annuario
        adapter_kwargs: {year: 2025}
        label: "2025"                       

  vodafone:
    enabled: true
    sources:
      - file: vodafone_attendences_new.csv
        reader: csv
        adapter: vodafone_raw             # this includes year 2024 and 2025

  presenze_alb:
    enabled: true
    sources:
      - file: presenze_alb_2025.csv
        reader: ispat_apt_tsv
        adapter: presenze_ispat_apt
        adapter_kwargs: {year: 2025}

  presenze_extralb:
    enabled: true
    sources:
      - file: presenze_xalb_2025_prov.csv
        reader: ispat_grouped_tsv
        adapter: presenze_ispat_prov
        adapter_kwargs: {year: 2025}
