# SPDX-License-Identifier: Apache-2.0
"""
Loads and prepares the base "phenomenon" dataframes used to compute the
capacity / tourism indexes for Trentino, saves them in a format compatible with the Indicators/Phenomenon modules.

Each phenomenon dataframe is typically contains:
  - DATA: the time dimension, at whatever granularity is natural for that
    phenomenon (YYYY for yearly data, YYYY-MM-DD for daily data)
  - LOCATION: the comune/ambito name
  - COMUNE_ID: mapped location identifier(s), when available
  - ... plus the phenomenon's own value column(s)

NOTE ON ID_COMUNE FORMATTING: ISTAT comune codes are conventionally
represented as 6-digit zero-padded strings (e.g. 22001 -> "022001"). The
raw sources / mapping JSONs here store them as plain ints, so every
dataframe that carries an ID_COMUNE column is normalized to the
zero-padded string form right before it's returned, via `pad_id_comune()`.
"""

import logging
import pandas as pd

from utils.flows_utils.main_generate_flows_and_grids import (
    main_generate_flows_and_grids,
)
from data_preparation.v2.utils.utils import (
    get_s3,
    get_json_s3,
    pad_id_comune,
    get_mapping_comuni,
    save_computed_dfs,
)
from data_preparation.v2.utils.disaggregation import disaggregate

logging.basicConfig(level=logging.INFO)

FLUSSI_VALUE_COLS = [
    "FLOWS_IN",
    "FLOWS_OUT",
    "FLOWS_IN_TOURISTS",
    "FLOWS_OUT_TOURISTS",
    "FLOWS_IN_VISITORS",
    "FLOWS_OUT_VISITORS",
]
FLUSSI_LEVEL_COLS = [
    "LEVEL_IN",
    "LEVEL_OUT",
    "LEVEL_IN_TOURISTS",
    "LEVEL_OUT_TOURISTS",
    "LEVEL_IN_VISITORS",
    "LEVEL_OUT_VISITORS",
]


## UTILS FUNCTIONS
## Some functions for decoding / padding / cleaning


def create_mapping(df):
    """Utility function which creates mapping ISTAT IDS <> IDs"""

    extra_mapping = {
        "BENESELLO + CALLIANO + VOLANO": "BESENELLO + CALLIANO + VOLANO",
        "BORGO CHIESE + CASTEL CONDINO + PIEVE DI BONO-PREZ": "BORGO CHIESE + CASTEL CONDINO + PIEVE DI BONO-PREZZO",
        "PERGINE VALSUGANA + VIGNOLA-FALESINA (NORD)": "PERGINE VALSUGANA + VIGNOLA-FALESINA",
        "PERGINE VALSUGANA + VIGNOLA-FALESINA (SUD)": "PERGINE VALSUGANA + VIGNOLA-FALESINA",
        "RIVA DEL GARDA (PAESE)": "RIVA DEL GARDA",
        "RIVA DEL GARDA (SUL LAGO)": "RIVA DEL GARDA",
        "ROVERETO (BORGO SACCO)": "ROVERETO",
        "ROVERETO (CENTRO)": "ROVERETO",
        "ROVERETO (LIZZANA - OSPEDALE)": "ROVERETO",
        "ROVERETO (MARCO)": "ROVERETO",
        "ROVERETO (NORIGLIO)": "ROVERETO",
        "SANT'ORSOLA TERME + FRASSILONGO + PALU' DEL FERSIN": "SANT'ORSOLA TERME + FRASSILONGO + PALU' DEL FERSINA",
        "TN CENTRO": "TRENTO",
        "TN EST": "TRENTO",
        "TN NORD": "TRENTO",
        "TN OLTRE ADIGE NORD": "TRENTO",
        "TN OLTRE ADIGE SUD": "TRENTO",
        "TN SUD": "TRENTO",
    }

    df = df.copy()
    logging.info(
        "Downloading mapping_ids/mapping_comuni_into_vodafone_Trento.json from S3..."
    )
    mapping_comuni_voda = get_json_s3(
        "mapping_ids/mapping_comuni_into_vodafone_Trento.json"
    )
    df["codice_istat_voda"] = (
        df["comune"].str.upper().str.strip().map(mapping_comuni_voda)
    )

    df.loc[df["codice_istat_voda"].isna(), "codice_istat_voda"] = (
        df.loc[df["codice_istat_voda"].isna(), "comune"]
        .str.upper()
        .str.strip()
        .map(extra_mapping)
        .str.upper()
        .str.strip()
        .map(mapping_comuni_voda)
    )

    mask = df["comune"].isin(["VIGO DI FASSA", "POZZA DI FASSA"])
    df.loc[mask, "comune"] = "SAN GIOVANNI DI FASSA"
    for idx in df.index[mask]:
        df.at[idx, "codice_istat_voda"] = [22250]
    return dict(zip(df["ID"], df["codice_istat_voda"]))


## COMPUTATION
## Functions to compute phenomena dataframes


def compute_flussi_trentino(mapping_comuni):
    # NOTE: The following files are generated by the diffusion process. For the moment they are uploaded on atlas, TODO: decide whether integrate the process or mantain it external
    logging.info("Downloading grid_all_columns__.parquet from S3...")
    df_ = pd.read_parquet(get_s3("grid_all_columns__.parquet"))
    logging.info("Downloading grid_all_columns_user.parquet from S3...")
    df_u = pd.read_parquet(get_s3("grid_all_columns_user.parquet"))

    cols = [
        "AREA_ID",
        "AREA_LABEL",
        "hotspot_level_tot_in_flows_t_0_0_w_all_days_d_",
        "tot_in_flows_t_0_0_w_all_days_d_",
        "hotspot_level_tot_out_flows_t_0_0_w_all_days_d_",
        "tot_out_flows_t_0_0_w_all_days_d_",
    ]
    ## Mappatura colonne dati parquet completo
    df__map = {
        "AREA_ID": "ID",
        "AREA_LABEL": "comune",
        "tot_in_flows_t_0_0_w_all_days_d_": "FLOWS_IN",
        "tot_out_flows_t_0_0_w_all_days_d_": "FLOWS_OUT",
        "hotspot_level_tot_in_flows_t_0_0_w_all_days_d_": "LEVEL_IN",
        "hotspot_level_tot_out_flows_t_0_0_w_all_days_d_": "LEVEL_OUT",
    }

    df_flussi_all = df_[cols].copy()
    df_flussi_all = df_flussi_all[
        df_flussi_all["AREA_ID"].str.startswith("ITA.04.022.", na=False)
    ]

    # TODO: MANAGE DIFFERENTLY (this operation of multiplying was done in original file)
    df_flussi_all["tot_in_flows_t_0_0_w_all_days_d_"] *= 4
    df_flussi_all["tot_out_flows_t_0_0_w_all_days_d_"] *= 4

    df_flussi_all.rename(columns=df__map, inplace=True)
    df_flussi_all["comune"] = df_flussi_all["comune"].str.upper()

    ## Mappatura colonne dati Utenti / Escursionisti / Turisti
    cols_user = [
        "AREA_ID",
        "AREA_LABEL",
        "hotspot_level_tot_in_flows_TOURIST_t_0_0_w_all_days_d_",
        "tot_in_flows_TOURIST_t_0_0_w_all_days_d_",
        "hotspot_level_tot_out_flows_TOURIST_t_0_0_w_all_days_d_",
        "tot_out_flows_TOURIST_t_0_0_w_all_days_d_",
        "hotspot_level_tot_in_flows_VISITOR_t_0_0_w_all_days_d_",
        "tot_in_flows_VISITOR_t_0_0_w_all_days_d_",
        "hotspot_level_tot_out_flows_VISITOR_t_0_0_w_all_days_d_",
        "tot_out_flows_VISITOR_t_0_0_w_all_days_d_",
    ]
    df_u_map = {
        "AREA_ID": "ID",
        "AREA_LABEL": "comune",
        "hotspot_level_tot_in_flows_TOURIST_t_0_0_w_all_days_d_": "LEVEL_IN_TOURISTS",
        "tot_in_flows_TOURIST_t_0_0_w_all_days_d_": "FLOWS_IN_TOURISTS",
        "hotspot_level_tot_out_flows_TOURIST_t_0_0_w_all_days_d_": "LEVEL_OUT_TOURISTS",
        "tot_out_flows_TOURIST_t_0_0_w_all_days_d_": "FLOWS_OUT_TOURISTS",
        "hotspot_level_tot_in_flows_VISITOR_t_0_0_w_all_days_d_": "LEVEL_IN_VISITORS",
        "tot_in_flows_VISITOR_t_0_0_w_all_days_d_": "FLOWS_IN_VISITORS",
        "hotspot_level_tot_out_flows_VISITOR_t_0_0_w_all_days_d_": "LEVEL_OUT_VISITORS",
        "tot_out_flows_VISITOR_t_0_0_w_all_days_d_": "FLOWS_OUT_VISITORS",
    }

    df_flussi_all_user = df_u[cols_user].copy()
    df_flussi_all_user = df_flussi_all_user[
        df_flussi_all_user["AREA_ID"].str.startswith("ITA.04.022.", na=False)
    ]
    df_flussi_all_user.rename(columns=df_u_map, inplace=True)
    df_flussi_all_user["comune"] = df_flussi_all_user["comune"].str.upper()

    df_merged = pd.merge(
        df_flussi_all,
        df_flussi_all_user,
        on=["ID", "comune"],
        how="outer",
        indicator=True,
    )
    if len(df_merged[df_merged["_merge"] != "both"]) > 0:
        logging.warning(
            "WARNING: discrepancies found in IDs: ",
            len(df_merged[df_merged["_merge"] != "both"]),
        )
    df_merged["DATA"] = 2024
    id_map = create_mapping(df_flussi_all_user[["ID", "comune"]])
    df_merged["ID_COMUNE"] = df_merged["ID"].map(id_map)

    value_cols, level_cols = FLUSSI_VALUE_COLS, FLUSSI_LEVEL_COLS
    df_merged = disaggregate(
        df_merged,
        cols=value_cols,
        axis="space",
        group_col="comune",
        id_to_name={id_comune: name for name, id_comune in mapping_comuni.items()},
    )

    agg_dict = {
        **{col: "sum" for col in value_cols},
        **{col: "median" for col in level_cols},
    }
    df_merged = (
        df_merged.groupby(["DATA", "ID_COMUNE", "comune"]).agg(agg_dict).reset_index()
    )  # For the moment, use median for the level
    df_merged["ID_COMUNE"] = pad_id_comune(df_merged["ID_COMUNE"])
    return df_merged


def compute_flussi_2023_temp(flussi_df):
    """Compute a temporary version of the flussi dataframe for 2023, using the 2024 data as a proxy.
    NOTE: IMPORTANT: This is a temporary solution, and should be replaced with actual data when available.
    """
    flussi_temp_2023 = flussi_df.copy()
    flussi_temp_2023["DATA"] = 2023
    return flussi_temp_2023


## MAIN computation of phenomena
def compute_phenomenon_dataframes(local=False):
    """Loads and prepares the base "phenomenon" dataframes.

    Returns a dict with keys:
      "phen_flussi", "phen_flussi_temp_2023",
    Each value is a dataframe standardized to DATA/LOCATION (+ ID, + the
    phenomenon's own value columns). Any ID_COMUNE column is zero-padded to
    6 digits (e.g. 22001 -> "022001").
    """

    # Preprocessing step
    logging.info("Diffusion preprocessing step")
    main_generate_flows_and_grids(local=local)

    logging.info(f"## Computing phenomenon dataframes")
    mapping_comuni = get_mapping_comuni()

    flussi_df = compute_flussi_trentino(mapping_comuni)
    phen_flussi_temp_2023 = compute_flussi_2023_temp(flussi_df)

    dict_dfs = {
        "phen_flussi": flussi_df,
        "phen_flussi_temp_2023": phen_flussi_temp_2023,
    }

    save_computed_dfs(dict_dfs, local=local)


if __name__ == "__main__":
    compute_phenomenon_dataframes(local=True)
